Gradle 4.0.0 autoupdated due to (+) specification on dependency
Released yesterday, the gradle 4.0.0 version causes this compilation error:
```Application build has failed with an error (Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.60-eap-25)````

Source: https://androidstudio.googleblog.com/2019/10/android-studio-40-canary-1-available.html
More info: https://stackoverflow.com/questions/58529904/error-could-not-find-org-jetbrains-kotlinkotlin-stdlib-jdk81-3-60-eap-25-in-i/58536638#58536638

This pull request reverts the dependency to the last working version.

It is always a good practice to freeze dependencies to achieve reliable builds over time.